dotVersionFiles:
  - api/rust/core/Cargo.toml
  - api/rust/codegen/Cargo.toml
  - api/assemblyscript/package.json

preMakeTargets:
  - test
  - crate/check

postMakeTargets:
  - crate/publish
  - npm/publish