name: Testapalooza

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    strategy:
        matrix:
          os: [ubuntu-latest, macos-latest]
          golang: [1.17]

    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
        id: go

      - name: Install Subo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo clone suborbital/subo
          cd subo
          gh pr checkout 113
          make subo
          cd ../
          rm -rf subo

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get ./...

      - name: Build testdata
        run: |
          make testdata/docker
        
        # Test first with default (Wasmer) runtime, and then again with Wasmtime runtime
      - name: Run test
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          go test -v ./...
      
      - name: Run test with Wasmtime
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          go test -v --tags wasmtime ./...
